WIP: add DEBUG_REFCOUNT
In preparation for adding refcounts with a biased value, add checks that
refcounts have been correctly initialised prior to their first use.

NOTE: this relies on modifying the size of sk_ubff::cb as otherwise
there's not enough space:

| net/core/skbuff.c: In function 'msg_zerocopy_alloc':
| ././include/linux/compiler_types.h:335:45: error: call to '__compiletime_assert_715' declared with attribute error: BUILD_BUG_ON failed: sizeof(*uarg) > sizeof(skb->cb)

... and I suspect people will not be happy about that growing.

So far this results in a boot-time panic:

| Booting Linux on physical CPU 0x0000000000 [0x431f0af1]
| Linux version 5.16.0-rc4-00002-gca7bbda3895b (mark@lakrids) (aarch64-linux-gcc (GCC) 11.1.0, GNU ld (GNU Binutils) 2.36.1) #24 SMP PREEMPT Fri Dec 17 12:40:24 GMT 2021
| Machine model: linux,dummy-virt
| earlycon: pl11 at MMIO 0x0000000009000000 (options '')
| printk: bootconsole [pl11] enabled
| efi: UEFI not found.
| Kernel panic - not syncing: BUG: refcount 0xffff59a07efed528 has bad magic 0x00000000
| CPU: 0 PID: 0 Comm: swapper Not tainted 5.16.0-rc4-00002-gca7bbda3895b #24
| Hardware name: linux,dummy-virt (DT)
| Call trace:
|  dump_backtrace+0x0/0x1c0
|  show_stack+0x1c/0x70
|  dump_stack_lvl+0x68/0x84
|  dump_stack+0x1c/0x38
|  panic+0x15c/0x31c
|  get_unaligned_be32+0x0/0x14
|  kobject_get+0x84/0xf0
|  of_node_get+0x24/0x40
|  of_find_node_opts_by_path+0x17c/0x1a0
|  of_alias_scan+0x40/0x24c
|  unflatten_device_tree+0x44/0x54
|  setup_arch+0x288/0x5f0
|  start_kernel+0x84/0x65c
|  __primary_switched+0xc0/0xc8
| ---[ end Kernel panic - not syncing: BUG: refcount 0xffff59a07efed528 has bad magic 0x00000000 ]---

... which is apparently a refcount_inc() on zero:

| [mark@lakrids:~/src/linux]% ARCH=arm64 CROSS_COMPILE=aarch64-linux- usekorg 11.1.0 ./scripts/faddr2line vmlinux kobject_get+0x84/0xf0
| kobject_get+0x84/0xf0:
| arch_static_branch_jump at arch/arm64/include/asm/jump_label.h:38
| (inlined by) system_uses_lse_atomics at arch/arm64/include/asm/lse.h:24
| (inlined by) arch_atomic_fetch_add_relaxed at arch/arm64/include/asm/atomic.h:49
| (inlined by) atomic_fetch_add_relaxed at include/linux/atomic/atomic-instrumented.h:112
| (inlined by) __refcount_add at include/linux/refcount.h:227
| (inlined by) __refcount_inc at include/linux/refcount.h:286
| (inlined by) refcount_inc at include/linux/refcount.h:304
| (inlined by) kref_get at include/linux/kref.h:45
| (inlined by) kobject_get at lib/kobject.c:659

TODO:

* Refactor the __refcount_* and refcount_* functions so that internal functions
  don't duplicate the check.

* Add a refcount_init() for dynamically-allocated objects?

Signed-off-by: Mark Rutland <mark.rutland@arm.com>