kcsan: remove atomic builtin support
Support for the compiler builtin atomic operations was added mostly for
the benefit of s390 in commit:

  0f8ad5f2e9342581 (“kcsan: Add support for atomic builtins”)

Since then, s390 moved away from the builtins in commit:

  b23eb636d7f9f3d7 (“s390/atomic: get rid of gcc atomic builtins”)

... and other kernel code steers clear of the builtins, leaving the
kcsan_test module as the only deliberate user of the atomic builtins on
an arch supported by KCSAN.

On arm64, compilers may default to using "outline atomics", where the
builtins result in calls to out-of-line functions which we do not
provide implementations of, resuilting in link-time failures when using
KCSAN, e.g.

| aarch64-linux-ld: kernel/kcsan/core.o: in function `__tsan_atomic8_exchange':
| /home/mark/src/linux/kernel/kcsan/core.c:1048: undefined reference to `__aarch64_swp1_acq_rel'
| aarch64-linux-ld: /home/mark/src/linux/kernel/kcsan/core.c:1048: undefined reference to `__aarch64_swp1_acq_rel'

As we do not intend to use the builtins on arm64, and other
architectures supporting KCSAN have moved away from using the builtins,
we can solve this by removing support for the builtins.

This patch removes support for the builtins.

Signed-off-by: Mark Rutland <mark.rutland@arm.com>
Cc: Marco Elver <elver@google.com>
Cc: Paul E. McKenney <paulmck@kernel.org>